# syntax=docker/dockerfile:1
# https://docs.docker.com/samples/django/
FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/